[build]
target = "crates/client/index.html"
dist = "dist"
public_url = "/"

[serve]
port = 8080
open = false

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "cd crates/client && cargo build --target wasm32-unknown-unknown"]
